import express from "express";
import { readFileSync, existsSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import kuromoji from "kuromoji";
import Database from "better-sqlite3";
import {
  createEmbeddingAdapter,
  createGenerationAdapter,
} from "./adapters/index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Config ────────────────────────────────────────────────────────────────────

const configPath = join(__dirname, "config.json");
if (!existsSync(configPath)) {
  console.error(
    "config.json not found. Copy config.example.json and fill in your values.",
  );
  process.exit(1);
}
const cfg = JSON.parse(readFileSync(configPath, "utf8"));

const PORT = cfg.port || process.env.PORT || 3000;

const embedAdapter = createEmbeddingAdapter(cfg, "embedding");
const enhanceAdapter = createGenerationAdapter(cfg, "enhance");
const storyAdapter = createGenerationAdapter(cfg, "story");

// ── Startup data ──────────────────────────────────────────────────────────────

const vocabByLevel = JSON.parse(
  readFileSync(join(__dirname, "vocabulary.json"), "utf8"),
);
const kanjiByLevel = JSON.parse(
  readFileSync(join(__dirname, "kanji.json"), "utf8"),
);

const embIndex = JSON.parse(
  readFileSync(join(__dirname, "vocab_embeddings_index.json"), "utf8"),
);
const embBuf = readFileSync(join(__dirname, "vocab_embeddings.bin"));

// JMdict SQLite — local dictionary for unknown-word resolution and popups.
// Built once by: node scripts/build_dict.js
const dictDbPath = join(__dirname, "dict.sqlite");
const dictStmt = existsSync(dictDbPath)
  ? new Database(dictDbPath, { readonly: true }).prepare(
      "SELECT reading, meanings, pos FROM dict WHERE word = ?",
    )
  : null;
if (dictStmt) console.log("Loaded dict.sqlite.");
else console.warn("dict.sqlite not found — run: node scripts/build_dict.js");

// Anki comfort scores — optional, generated by scripts/anki_sync.py --with-metadata
// { "学校": { comfort: 0.95, level: 7, kind: "vocabulary" }, ... }
// Falls back gracefully: unreviewed words get a neutral weight.
const comfortPath = join(__dirname, "vocab_comfort.json");
const comfortMap = new Map();
const reviewsMap = new Map();
if (existsSync(comfortPath)) {
  const raw = JSON.parse(readFileSync(comfortPath, "utf8"));
  for (const [word, entry] of Object.entries(raw)) {
    if (entry.kind === "radical") continue; // not useful for story vocab
    comfortMap.set(word, typeof entry === "number" ? entry : entry.comfort);
    if (typeof entry === "object" && entry.reviews !== undefined)
      reviewsMap.set(word, entry.reviews);
  }
  console.log(`Loaded comfort scores for ${comfortMap.size} words.`);
}

// Dimensions come from the index — it's the source of truth for what's stored.
const EMBED_DIM = embIndex.meta.dimensions;
const embVecs = new Float32Array(
  embBuf.buffer,
  embBuf.byteOffset,
  embBuf.byteLength / 4,
);

const tokenizer = await new Promise((resolve, reject) =>
  kuromoji
    .builder({ dicPath: join(__dirname, "node_modules/kuromoji/dict") })
    .build((err, t) => (err ? reject(err) : resolve(t))),
);

// ── POS tagging ───────────────────────────────────────────────────────────────

function classifyPos(character) {
  const t = tokenizer.tokenize(character)[0];
  if (!t) return "other";
  const { pos, pos_detail_1: pos1 } = t;
  if (pos === "動詞") return "verb";
  if (pos === "形容詞") return "i-adj";
  if (pos === "副詞") return "adverb";
  if (pos === "連体詞") return "adj";
  if (pos === "名詞") {
    if (pos1 === "形容動詞語幹") return "na-adj";
    if (pos1 === "サ変接続") return "suru-noun";
    if (pos1 === "数") return "number";
    return "noun";
  }
  return "other";
}

const posMap = new Map();
for (const item of embIndex.items)
  posMap.set(item.row, classifyPos(item.character));

console.log("Ready.");

// ── Helpers ───────────────────────────────────────────────────────────────────

// Returns a POS-balanced set of vocab items filtered to levels ≤ maxLevel.
// Target mix: ~13 nouns, ~4 suru-nouns, ~7 verbs, ~5 adjectives, ~2 adverbs,
// plus wildcards sampled from ranks 20–100 to fill to 42.
function retrieveVocab(queryVec, maxLevel) {
  const rowCount = embIndex.maxRowByLevel[maxLevel] ?? embIndex.meta.count;
  const scores = new Array(rowCount);

  for (let r = 0; r < rowCount; r++) {
    const base = r * EMBED_DIM;
    let dot = 0;
    for (let i = 0; i < EMBED_DIM; i++) dot += queryVec[i] * embVecs[base + i];
    // If comfort data is available: reviewed words get a boost scaled by how
    // much they're struggling (2 - comfort); unreviewed words are heavily
    // suppressed since the user hasn't learned them yet.
    // Without comfort data: neutral weight, level filter is the only gate.
    const comfort = comfortMap.get(embIndex.items[r].character);
    const weight =
      comfortMap.size > 0 ? (comfort !== undefined ? 2 - comfort : 0.1) : 1.0;
    scores[r] = { r, dot: dot * weight, pos: posMap.get(r) };
  }
  scores.sort((a, b) => b.dot - a.dot);

  // Bucket by POS (preserving similarity order within each bucket)
  const noun = scores.filter((s) => s.pos === "noun" || s.pos === "other");
  const suruNoun = scores.filter((s) => s.pos === "suru-noun");
  const verb = scores.filter((s) => s.pos === "verb");
  const adj = scores.filter(
    (s) => s.pos === "i-adj" || s.pos === "na-adj" || s.pos === "adj",
  );
  const adverb = scores.filter((s) => s.pos === "adverb");

  const picked = new Set();
  const result = [];

  function pickTop(bucket, n) {
    let count = 0;
    for (const s of bucket) {
      if (count >= n) break;
      if (!picked.has(s.r)) {
        picked.add(s.r);
        result.push({ ...embIndex.items[s.r], pos: s.pos });
        count++;
      }
    }
  }

  pickTop(noun, 26);
  pickTop(suruNoun, 8);
  pickTop(verb, 14);
  pickTop(adj, 10);
  pickTop(adverb, 4);

  // Wildcards: random sample from overall ranks 20–200, skip numbers + proper nouns
  const wildcardPool = scores
    .slice(20, 200)
    .filter((s) => !picked.has(s.r) && s.pos !== "number");
  while (result.length < 84 && wildcardPool.length > 0) {
    const i = Math.floor(Math.random() * wildcardPool.length);
    const s = wildcardPool.splice(i, 1)[0];
    picked.add(s.r);
    result.push({ ...embIndex.items[s.r], pos: s.pos });
  }

  // Recently-learned injection: tack on up to 2 words reviewed only a handful of
  // times, drawn from the top 150 similarity-ranked candidates so they're at least
  // loosely on-theme. Skipped silently if there aren't enough qualifying words.
  if (reviewsMap.size > 0) {
    const recentPool = scores
      .slice(0, 150)
      .filter(
        (s) =>
          !picked.has(s.r) &&
          s.pos !== "number" &&
          reviewsMap.get(embIndex.items[s.r].character) === 1,
      );
    for (let i = 0; i < 2 && recentPool.length > 0; i++) {
      const idx = Math.floor(Math.random() * Math.min(recentPool.length, 20));
      const s = recentPool.splice(idx, 1)[0];
      picked.add(s.r);
      result.push({ ...embIndex.items[s.r], pos: s.pos });
    }
  }

  return result;
}

// Groups a kuromoji POS tag into a broad category for neighbour matching.
function posCategory(pos) {
  if (pos === "verb") return "verb";
  if (pos === "suru-noun") return "suru-noun";
  if (pos === "i-adj" || pos === "na-adj" || pos === "adj") return "adj";
  if (pos === "adverb") return "adverb";
  return "noun";
}

// Find the N nearest WaniKani neighbours of a vocab row within maxLevel,
// excluding any row in excludeRows. Synchronous — uses in-memory vectors.
function getNeighborRows(sourceRow, maxLevel, n, excludeRows) {
  const rowCount = embIndex.maxRowByLevel[maxLevel] ?? embIndex.meta.count;
  const srcBase = sourceRow * EMBED_DIM;
  const scores = [];
  for (let r = 0; r < rowCount; r++) {
    if (excludeRows.has(r)) continue;
    const base = r * EMBED_DIM;
    let dot = 0;
    for (let i = 0; i < EMBED_DIM; i++)
      dot += embVecs[srcBase + i] * embVecs[base + i];
    scores.push({ r, dot });
  }
  scores.sort((a, b) => b.dot - a.dot);
  return scores
    .slice(0, n)
    .map((s) => ({ ...embIndex.items[s.r], pos: posMap.get(s.r) }));
}

// Embed an arbitrary word and find its nearest WaniKani neighbours within
// maxLevel. Used by the correction pass for unknown-word replacement.
function tokenize(text) {
  return tokenizer.tokenize(text).map((t) => {
    let dict = t.basic_form || t.surface_form;
    if (dict.endsWith("な") && /[ぁ-ん]/.test(dict.slice(-2, -1)))
      dict = dict.slice(0, -1) + "い";
    return { surface: t.surface_form, dict, reading: t.reading || "" };
  });
}

function itemsUpToLevel(byLevel, maxLevel) {
  const out = [];
  for (let i = 1; i <= maxLevel; i++)
    for (const item of byLevel[String(i)] || [])
      out.push({ ...item, level: i });
  return out;
}

// ── Express ───────────────────────────────────────────────────────────────────

const app = express();
app.use(express.json());
app.use(express.static(join(__dirname, "public")));

app.get("/api/data/:maxLevel", (req, res) => {
  const maxLevel = Math.min(
    60,
    Math.max(1, parseInt(req.params.maxLevel) || 1),
  );
  res.json({
    vocab: itemsUpToLevel(vocabByLevel, maxLevel),
    kanji: itemsUpToLevel(kanjiByLevel, maxLevel),
    allVocab: itemsUpToLevel(vocabByLevel, 60),
    allKanji: itemsUpToLevel(kanjiByLevel, 60),
  });
});

app.get("/api/placeholder", async (req, res) => {
  const maxLevel = Math.min(60, Math.max(1, parseInt(req.query.level) || 5));

  const maxRow = embIndex.maxRowByLevel[maxLevel] ?? embIndex.meta.count;
  const pool = embIndex.items.slice(0, maxRow);

  // Pick ~12 seeds with loose POS balance so the LLM has real thematic material.
  // Aim for at least 4 nouns and 3 verbs/adjectives; fill the rest randomly.
  const used = new Set();
  const seeds = [];
  function pickCategory(filter, n) {
    const candidates = pool
      .map((w, i) => ({ w, i }))
      .filter(({ w, i }) => !used.has(i) && filter(w));
    for (let c = 0; c < n && candidates.length > 0; c++) {
      const pick = candidates.splice(
        Math.floor(Math.random() * candidates.length),
        1,
      )[0];
      used.add(pick.i);
      seeds.push(pick.w);
    }
  }
  const isNoun = (w) => {
    const p = posMap.get(w.row);
    return p === "noun" || p === "other";
  };
  const isVerb = (w) => posMap.get(w.row) === "verb";
  const isAdj = (w) => {
    const p = posMap.get(w.row);
    return p === "i-adj" || p === "na-adj" || p === "adj";
  };
  pickCategory(isNoun, 4);
  pickCategory(isVerb, 3);
  pickCategory(isAdj, 2);
  // Fill remainder randomly up to 12
  while (seeds.length < 12 && seeds.length < pool.length) {
    const idx = Math.floor(Math.random() * pool.length);
    if (!used.has(idx)) {
      used.add(idx);
      seeds.push(pool[idx]);
    }
  }
  const wordList = seeds
    .map((w) => `${w.character} (${w.primary_meaning})`)
    .join(", ");

  try {
    const prompt = await enhanceAdapter.generate(
      "You write story prompts in the style of r/WritingPrompts — emotionally resonant, character-driven, with a specific human detail that makes them feel alive. " +
        "You will be given a list of Japanese vocabulary words as loose thematic inspiration. " +
        "Pick whichever words spark something interesting and ignore the rest — never try to use all of them, and never shoehorn a word in just because it's on the list. " +
        "The prompt should feel like something a person genuinely wants to read: a situation with real emotional stakes, a small irony, or a poignant detail. " +
        "Write one sentence. Output only the sentence — no preamble, no label like 'Prompt:', no quotes.",
      `Inspiration words: ${wordList}`,
      { thinkingConfig: { thinkingBudget: 0 } },
    );
    res.json({ prompt: prompt.trim().replace(/^prompt:\s*/i, "") });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/generate", async (req, res) => {
  const {
    level = 5,
    prompt: userPrompt = "Write a short story.",
    context = "",
  } = req.body;
  const maxLevel = Math.min(60, Math.max(1, parseInt(level) || 1));
  const vocabLevel = Math.max(maxLevel, 5);

  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();

  const send = (type, data) =>
    res.write(`data: ${JSON.stringify({ type, data })}\n\n`);

  try {
    send("status", "Finding vocabulary...");

    const retrievalQuery = await enhanceAdapter
      .generate(
        "You help retrieve relevant Japanese vocabulary for a story prompt. " +
          "Given a story prompt, list the key themes, objects, places, actions, emotions, and relationships in the story — not as a scene description, but as a flat, diverse set of concepts that would help retrieve relevant vocabulary words. " +
          "Include both the obvious elements and subtler ones (e.g. mood, time of day, character relationships). " +
          "Output only the list, no preamble, no explanation.",
        `Story prompt: ${userPrompt}`,
        { thinkingConfig: { thinkingBudget: 0 } },
      )
      .catch(() => userPrompt);

    const queryVec = await embedAdapter.embed(retrievalQuery);
    const selectedVocab = retrieveVocab(queryVec, vocabLevel);
    send(
      "words",
      selectedVocab.map((w) => w.character),
    );

    send("status", "Generating...");

    // Build word list with 2 same-category neighbours per word as alternatives.
    // Neighbours are sourced from the level-capped embedding space using in-memory
    // dot products — no API calls. usedRows prevents the same word appearing in
    // multiple groups.
    const usedRows = new Set(selectedVocab.map((w) => w.row));
    const posGroups = {
      nouns: [],
      "suru-verbs": [],
      verbs: [],
      adjectives: [],
      adverbs: [],
    };

    for (const w of selectedVocab) {
      const cat = posCategory(w.pos);
      const neighbors = getNeighborRows(w.row, vocabLevel, 20, usedRows)
        .filter((n) => posCategory(n.pos) === cat)
        .slice(0, 2);
      neighbors.forEach((n) => usedRows.add(n.row));

      const group = [w.character, ...neighbors.map((n) => n.character)].join(
        " / ",
      );

      if (w.pos === "suru-noun") posGroups["suru-verbs"].push(group);
      else if (w.pos === "verb") posGroups.verbs.push(group);
      else if (w.pos === "i-adj" || w.pos === "na-adj" || w.pos === "adj")
        posGroups.adjectives.push(group);
      else if (w.pos === "adverb") posGroups.adverbs.push(group);
      else posGroups.nouns.push(group);
    }

    const wordList = Object.entries(posGroups)
      .filter(([, groups]) => groups.length > 0)
      .map(([pos, groups]) => `${pos}:\n\`\`\`\n${groups.join("\n")}\n\`\`\``)
      .join("\n\n");
    const storyContext = context
      ? `The story so far:\n${context}\n\nContinue from where it left off. End at a new moment of tension — complete your final sentence but leave the situation unresolved.\n\n- Words already in the story are freely available; the provided list is additional vocabulary, not a replacement.\n- Keep character names and nouns consistent. Do not introduce 彼女 or switch names.\n- Maintain plain form (常体) and consistent tense throughout.`
      : `Story theme: ${userPrompt}`;

    const systemPrompt = [
      `You are an expert Japanese author writing a short-short (ショートショート) story for a Japanese learner.`,
      ``,
      `Write in clear, natural Japanese, with the compact feel of 星新一 or modern Japanese YA prose.`,
      `Aim for one coherent scenario, not a tour through many unrelated ideas.`,
      ``,
      `Before writing, silently decide:`,
      `- one focal character or narrator`,
      `- one concrete setting`,
      `- one specific object, creature, or detail that anchors the story`,
      `- a simple arc: setup → development → tension → one final image or action that makes the whole story click into place`,
      `- a small subset of the allowed vocabulary that best fits this story`,
      ``,
      `Style:`,
      `- Write exactly 8–10 sentences.`,
      `- Plain form (常体) for narration.`,
      `- Dialogue should match the speaker naturally.`,
      `- Keep a single stable viewpoint throughout.`,
      `- Prefer concrete actions and images over abstract explanation.`,
      ``,
      `Vocabulary:`,
      `- Content words (nouns, verbs, adjectives, adverbs) must come from the provided vocabulary only.`,
      `- Inflected forms are allowed: 食べる → 食べた / 食べよう / 食べながら etc.`,
      `- Grammar, particles, and function words are unrestricted.`,
      `- Use a natural subset of the vocabulary. Do not force every word in.`,
      `- If a concept would require an unlisted content word, change the scene, event, or phrasing instead.`,
      `- Exception: character names, place names, and proper nouns from the story theme may be used freely — write them in katakana.`,
      ``,
      `When the vocabulary is shown as alternatives separated by /:`,
      `- choose the word that fits the actual image you are describing`,
      `- prefer the most specific and concrete option, not the broadest or safest category word`,
      ``,
      `Narration:`,
      `- Establish the actor once, then omit the subject naturally in later sentences unless clarity requires it.`,
      `- After the first 1–2 sentences, explicit subjects in narration should be rare.`,
      `- Do not use 彼 or 彼女 for the focal character in narration; omit the subject or use the role/name if needed.`,
      ``,
      `Before finalising, silently check:`,
      `- the story stays in one coherent scenario`,
      `- the ending feels implied by the setup, not random`,
      `- explicit subjects are not repeated unnecessarily`,
      `- content words stay within the provided vocabulary`,
      ``,
      `Output ONLY the Japanese story. No title, no preamble, no plan, no English.`,
    ].join("\n");

    // ── First pass: stream to client immediately ─────────────────────────────────────
    let raw = "";
    await storyAdapter.stream(
      systemPrompt,
      `Known vocabulary list (words separated by / on the same line are semantic alternatives — use whichever fits best):\n${wordList}\n\n${storyContext}`,
      { thinkingConfig: { thinkingBudget: 0 } },
      (chunk) => {
        raw += chunk;
        send("delta", chunk);
      },
    );

    send("done", { tokens: tokenize(raw) });
  } catch (err) {
    console.error(err);
    send("error", err.message || "Generation failed");
  } finally {
    res.end();
  }
});

// ── Dictionary lookup (local JMdict) ────────────────────────────────────────

app.get("/api/dict", (req, res) => {
  const { word } = req.query;
  if (!word) return res.status(400).json({ error: "word required" });
  if (!dictStmt) return res.json({ found: false });
  const row = dictStmt.get(word);
  if (!row) return res.json({ found: false });
  res.json({
    found: true,
    reading: row.reading,
    meanings: JSON.parse(row.meanings),
    partsOfSpeech: JSON.parse(row.pos),
  });
});

app.post("/api/explain", async (req, res) => {
  const { text, story } = req.body;
  if (!text) return res.status(400).json({ error: "text required" });

  try {
    const explanation = await enhanceAdapter.generate(
      "You are a Japanese grammar tutor helping a WaniKani learner read a story. " +
        "The full story is provided for context. The specific word or phrase the learner is asking about is marked with << >> delimiters. " +
        "Explain in 1-2 sentences how the marked word/phrase functions grammatically in its immediate clause. " +
        "Ground your explanation in the actual content \u2014 name the real subject, object, or situation rather than speaking abstractly. " +
        "If the word appears to be used in an unusual or unexpected way given the story context, note that briefly. " +
        "Do NOT summarise the story. Do NOT restate the dictionary meaning or give the reading. " +
        "Start directly with the grammatical function. Plain English. No intro phrases.",
      `Story:\n${story}\n\nHighlighted: ${text}`,
      { thinkingConfig: { thinkingBudget: 0 }, maxOutputTokens: 200 },
    );
    res.json({ explanation: explanation.trim() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.listen(PORT, "0.0.0.0", () => console.log(`http://localhost:${PORT}`));
