import express from "express";
import { readFileSync, existsSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import kuromoji from "kuromoji";
import Database from "better-sqlite3";
import { createEmbeddingAdapter, createGenerationAdapter } from "./adapters/index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Config ────────────────────────────────────────────────────────────────────

const configPath = join(__dirname, "config.json");
if (!existsSync(configPath)) {
  console.error("config.json not found. Copy config.example.json and fill in your values.");
  process.exit(1);
}
const cfg = JSON.parse(readFileSync(configPath, "utf8"));

const PORT = cfg.port || process.env.PORT || 3000;

const embedAdapter   = createEmbeddingAdapter(cfg, "embedding");
const enhanceAdapter = createGenerationAdapter(cfg, "enhance");
const storyAdapter   = createGenerationAdapter(cfg, "story");

// ── Startup data ──────────────────────────────────────────────────────────────

const vocabByLevel = JSON.parse(readFileSync(join(__dirname, "vocabulary.json"), "utf8"));
const kanjiByLevel = JSON.parse(readFileSync(join(__dirname, "kanji.json"), "utf8"));

const embIndex = JSON.parse(readFileSync(join(__dirname, "vocab_embeddings_index.json"), "utf8"));
const embBuf   = readFileSync(join(__dirname, "vocab_embeddings.bin"));

// JMdict SQLite — local dictionary for unknown-word resolution and popups.
// Built once by: node scripts/build_dict.js
const dictDbPath = join(__dirname, "dict.sqlite");
const dictStmt   = existsSync(dictDbPath)
  ? new Database(dictDbPath, { readonly: true })
      .prepare("SELECT reading, meanings, pos FROM dict WHERE word = ?")
  : null;
if (dictStmt) console.log("Loaded dict.sqlite.");
else          console.warn("dict.sqlite not found — run: node scripts/build_dict.js");

// Anki comfort scores — optional, generated by scripts/anki_sync.py --with-metadata
// { "学校": { comfort: 0.95, level: 7, kind: "vocabulary" }, ... }
// Falls back gracefully: unreviewed words get a neutral weight.
const comfortPath = join(__dirname, "vocab_comfort.json");
const comfortMap  = new Map();
const reviewsMap  = new Map();
if (existsSync(comfortPath)) {
  const raw = JSON.parse(readFileSync(comfortPath, "utf8"));
  for (const [word, entry] of Object.entries(raw)) {
    if (entry.kind === "radical") continue;  // not useful for story vocab
    comfortMap.set(word, typeof entry === "number" ? entry : entry.comfort);
    if (typeof entry === "object" && entry.reviews !== undefined)
      reviewsMap.set(word, entry.reviews);
  }
  console.log(`Loaded comfort scores for ${comfortMap.size} words.`);
}

// Dimensions come from the index — it's the source of truth for what's stored.
const EMBED_DIM = embIndex.meta.dimensions;
const embVecs   = new Float32Array(embBuf.buffer, embBuf.byteOffset, embBuf.byteLength / 4);

const tokenizer = await new Promise((resolve, reject) =>
  kuromoji
    .builder({ dicPath: join(__dirname, "node_modules/kuromoji/dict") })
    .build((err, t) => (err ? reject(err) : resolve(t)))
);

// ── POS tagging ───────────────────────────────────────────────────────────────

function classifyPos(character) {
  const t = tokenizer.tokenize(character)[0];
  if (!t) return "other";
  const { pos, pos_detail_1: pos1 } = t;
  if (pos === "動詞")  return "verb";
  if (pos === "形容詞") return "i-adj";
  if (pos === "副詞")  return "adverb";
  if (pos === "連体詞") return "adj";
  if (pos === "名詞") {
    if (pos1 === "形容動詞語幹") return "na-adj";
    if (pos1 === "サ変接続")    return "suru-noun";
    if (pos1 === "数")           return "number";
    return "noun";
  }
  return "other";
}

const posMap = new Map();
for (const item of embIndex.items) posMap.set(item.row, classifyPos(item.character));

console.log("Ready.");

// ── Helpers ───────────────────────────────────────────────────────────────────

// Returns a POS-balanced set of vocab items filtered to levels ≤ maxLevel.
// Target mix: ~13 nouns, ~4 suru-nouns, ~7 verbs, ~5 adjectives, ~2 adverbs,
// plus wildcards sampled from ranks 20–100 to fill to 42.
function retrieveVocab(queryVec, maxLevel) {
  const rowCount = embIndex.maxRowByLevel[maxLevel] ?? embIndex.meta.count;
  const scores   = new Array(rowCount);

  for (let r = 0; r < rowCount; r++) {
    const base    = r * EMBED_DIM;
    let dot = 0;
    for (let i = 0; i < EMBED_DIM; i++) dot += queryVec[i] * embVecs[base + i];
    // If comfort data is available: reviewed words get a boost scaled by how
    // much they're struggling (2 - comfort); unreviewed words are heavily
    // suppressed since the user hasn't learned them yet.
    // Without comfort data: neutral weight, level filter is the only gate.
    const comfort = comfortMap.get(embIndex.items[r].character);
    const weight  = comfortMap.size > 0
      ? (comfort !== undefined ? 2 - comfort : 0.1)
      : 1.0;
    scores[r] = { r, dot: dot * weight, pos: posMap.get(r) };
  }
  scores.sort((a, b) => b.dot - a.dot);

  // Bucket by POS (preserving similarity order within each bucket)
  const noun     = scores.filter(s => s.pos === "noun" || s.pos === "other");
  const suruNoun = scores.filter(s => s.pos === "suru-noun");
  const verb     = scores.filter(s => s.pos === "verb");
  const adj      = scores.filter(s => s.pos === "i-adj" || s.pos === "na-adj" || s.pos === "adj");
  const adverb   = scores.filter(s => s.pos === "adverb");

  const picked = new Set();
  const result = [];

  function pickTop(bucket, n) {
    let count = 0;
    for (const s of bucket) {
      if (count >= n) break;
      if (!picked.has(s.r)) {
        picked.add(s.r);
        result.push({ ...embIndex.items[s.r], pos: s.pos });
        count++;
      }
    }
  }

  pickTop(noun,     13);
  pickTop(suruNoun,  4);
  pickTop(verb,      7);
  pickTop(adj,       5);
  pickTop(adverb,    2);

  // Wildcards: random sample from overall ranks 20–100, skip numbers + proper nouns
  const wildcardPool = scores
    .slice(20, 100)
    .filter(s => !picked.has(s.r) && s.pos !== "number");
  while (result.length < 42 && wildcardPool.length > 0) {
    const i = Math.floor(Math.random() * wildcardPool.length);
    const s = wildcardPool.splice(i, 1)[0];
    picked.add(s.r);
    result.push({ ...embIndex.items[s.r], pos: s.pos });
  }

  // Recently-learned injection: tack on up to 2 words reviewed only a handful of
  // times, drawn from the top 150 similarity-ranked candidates so they're at least
  // loosely on-theme. Skipped silently if there aren't enough qualifying words.
  if (reviewsMap.size > 0) {
    const recentPool = scores
      .slice(0, 150)
      .filter(s => !picked.has(s.r)
                && s.pos !== "number"
                && reviewsMap.get(embIndex.items[s.r].character) === 1);
    for (let i = 0; i < 2 && recentPool.length > 0; i++) {
      const idx = Math.floor(Math.random() * Math.min(recentPool.length, 20));
      const s   = recentPool.splice(idx, 1)[0];
      picked.add(s.r);
      result.push({ ...embIndex.items[s.r], pos: s.pos });
    }
  }

  return result;
}

function tokenize(text) {
  return tokenizer.tokenize(text).map(t => {
    let dict = t.basic_form || t.surface_form;
    if (dict.endsWith("な") && /[ぁ-ん]/.test(dict.slice(-2, -1)))
      dict = dict.slice(0, -1) + "い";
    return { surface: t.surface_form, dict, reading: t.reading || "" };
  });
}

function itemsUpToLevel(byLevel, maxLevel) {
  const out = [];
  for (let i = 1; i <= maxLevel; i++)
    for (const item of byLevel[String(i)] || [])
      out.push({ ...item, level: i });
  return out;
}

// ── Express ───────────────────────────────────────────────────────────────────

const app = express();
app.use(express.json());
app.use(express.static(join(__dirname, "public")));

app.get("/api/data/:maxLevel", (req, res) => {
  const maxLevel = Math.min(60, Math.max(1, parseInt(req.params.maxLevel) || 1));
  res.json({
    vocab:    itemsUpToLevel(vocabByLevel, maxLevel),
    kanji:    itemsUpToLevel(kanjiByLevel, maxLevel),
    allVocab: itemsUpToLevel(vocabByLevel, 60),
    allKanji: itemsUpToLevel(kanjiByLevel, 60),
  });
});

app.get("/api/placeholder", async (req, res) => {
  const maxLevel = Math.min(60, Math.max(1, parseInt(req.query.level) || 5));

  const maxRow = embIndex.maxRowByLevel[maxLevel] ?? embIndex.meta.count;
  const pool   = embIndex.items.slice(0, maxRow);

  // Pick ~12 seeds with loose POS balance so the LLM has real thematic material.
  // Aim for at least 4 nouns and 3 verbs/adjectives; fill the rest randomly.
  const used  = new Set();
  const seeds = [];
  function pickCategory(filter, n) {
    const candidates = pool.map((w, i) => ({ w, i })).filter(({ w, i }) => !used.has(i) && filter(w));
    for (let c = 0; c < n && candidates.length > 0; c++) {
      const pick = candidates.splice(Math.floor(Math.random() * candidates.length), 1)[0];
      used.add(pick.i);
      seeds.push(pick.w);
    }
  }
  const isNoun = w => { const p = posMap.get(w.row); return p === "noun" || p === "other"; };
  const isVerb = w => posMap.get(w.row) === "verb";
  const isAdj  = w => { const p = posMap.get(w.row); return p === "i-adj" || p === "na-adj" || p === "adj"; };
  pickCategory(isNoun, 4);
  pickCategory(isVerb, 3);
  pickCategory(isAdj,  2);
  // Fill remainder randomly up to 12
  while (seeds.length < 12 && seeds.length < pool.length) {
    const idx = Math.floor(Math.random() * pool.length);
    if (!used.has(idx)) { used.add(idx); seeds.push(pool[idx]); }
  }
  const wordList = seeds.map(w => `${w.character} (${w.primary_meaning})`).join(", ");

  try {
    const prompt = await enhanceAdapter.generate(
      "You write story prompts in the style of r/WritingPrompts — emotionally resonant, character-driven, with a specific human detail that makes them feel alive. " +
      "You will be given a list of Japanese vocabulary words as loose thematic inspiration. " +
      "Pick whichever words spark something interesting and ignore the rest — never try to use all of them, and never shoehorn a word in just because it's on the list. " +
      "The prompt should feel like something a person genuinely wants to read: a situation with real emotional stakes, a small irony, or a poignant detail. " +
      "Write one sentence. Output only the sentence — no preamble, no label like 'Prompt:', no quotes.",
      `Inspiration words: ${wordList}`,
      { thinkingConfig: { thinkingBudget: 0 } }
    );
    res.json({ prompt: prompt.trim().replace(/^prompt:\s*/i, "") });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/generate", async (req, res) => {
  const { level = 5, prompt: userPrompt = "Write a short story.", context = "" } = req.body;
  const maxLevel   = Math.min(60, Math.max(1, parseInt(level) || 1));
  const vocabLevel = Math.max(maxLevel, 5);

  res.setHeader("Content-Type",  "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection",    "keep-alive");
  res.flushHeaders();

  const send = (type, data) => res.write(`data: ${JSON.stringify({ type, data })}\n\n`);

  try {
    send("status", "Finding vocabulary...");

    const retrievalQuery = await enhanceAdapter.generate(
      "You help retrieve relevant Japanese vocabulary for a story prompt. " +
      "Given a story prompt, list the key themes, objects, places, actions, emotions, and relationships in the story — not as a scene description, but as a flat, diverse set of concepts that would help retrieve relevant vocabulary words. " +
      "Include both the obvious elements and subtler ones (e.g. mood, time of day, character relationships). " +
      "Output only the list, no preamble, no explanation.",
      `Story prompt: ${userPrompt}`,
      { thinkingConfig: { thinkingBudget: 0 } }
    ).catch(() => userPrompt);

    const queryVec      = await embedAdapter.embed(retrievalQuery);
    const selectedVocab = retrieveVocab(queryVec, vocabLevel);
    send("words", selectedVocab.map(w => w.character));

    send("status", "Generating...");

    const posLabel = pos => {
      if (pos === "verb")      return "verb";
      if (pos === "suru-noun") return "noun/verb";
      if (pos === "i-adj" || pos === "na-adj" || pos === "adj") return "adj";
      if (pos === "adverb")   return "adverb";
      return "noun";
    };
    const wordList     = selectedVocab.map(w => `${w.character}[${posLabel(w.pos)}]`).join("、");
    const storyContext = context
      ? `The story so far:\n${context}\n\nContinue from where it left off. End at a new moment of genuine tension — complete your final sentence, but leave the situation unresolved.\n\nReminders for the continuation:\n- All the same vocabulary selection rules apply. Use only words from the provided list that fit naturally into where the story is going. Do not introduce new objects, details, or characters just to use vocabulary items.\n- Any word that already appeared in the story so far is also freely available to you — the provided list is additional vocabulary, not a replacement for what came before.\n- Maintain consistency with the story so far: use the same name or noun for each character (do not switch between 少女／女の子 or introduce 彼女).\n- Stay in plain form (常体) throughout. No です／ます in narration.\n- Keep tense consistent within each scene.`
      : `Story theme: ${userPrompt}`;

    const systemPrompt = [
      `You are writing Japanese reading practice for a WaniKani learner.`,
      ``,
      `The learner is at WaniKani level ${maxLevel}. However, the provided vocabulary list below is the complete source of truth for which content words the learner knows.`,
      ``,
      `Your task:`,
      `- Write one short, natural Japanese story of 10–15 sentences.`,
      `- Make it easy to read and easy to understand.`,
      `- Prioritise naturalness and flow over vocabulary coverage.`,
      ``,
      `Hard vocabulary rule:`,
      `- Every content word in the story must come from the provided vocabulary list.`,
      `- "Content words" includes nouns, verbs, adjectives, adverbs, and set phrases.`,
      `- Do not use synonyms, near-synonyms, paraphrases, or newly invented compounds unless the exact word is in the provided list.`,
      `- Do not convert unknown words into kana-only form to get around this rule.`,
      `- Do not introduce proper nouns, names, or place names unless they are in the provided list.`,
      `- Exception: character names, place names, and proper nouns from the story theme may be used freely — write them in katakana.`,
      ``,
      `Allowed grammar:`,
      `- You may freely use any standard Japanese grammar and function words: particles, copula, auxiliary verbs, inflectional endings, connective forms, and common conjunctions.`,
      `- This includes connective grammar such as 〜て、〜たり、〜し、〜から、〜が、〜けど、〜ので to join clauses naturally.`,
      `- If a sentence would require an out-of-list content word, simplify the sentence or plot instead. If the story theme itself requires a concept that cannot be expressed with the vocabulary list, drop or reframe that element — never introduce the word as a last resort.`,
      ``,
      `Vocabulary selection:`,
      `- Treat the vocabulary list as a permission list, not a checklist.`,
      `- Choose a small subset of words that fit one coherent scenario and build the story around that.`,
      `- Ignore any word that would make the story feel forced, random, or surreal.`,
      `- Never mention an item just to say it is absent, irrelevant, or nearby.`,
      `- Do not list items in sequence (e.g. 三月、四月、五月 or 四つ、五つ、六つ) just to use more vocabulary — pick one and move on.`,
      `- If the prompt mentions multiple characters, include all of them. Do not silently drop characters.`,
      ``,
      `Register:`,
      `- Write all narrative prose in plain form (常体): end sentences with だ、plain verbs, or plain adjectives. Never use です／ます in narration.`,
      `- Dialogue should match how each character would naturally speak — a child or teenager speaks casually, an elderly shopkeeper may speak more gruffly, etc.`,
      ``,
      `Japanese naturalness rules:`,
      `- Vary sentence endings. Do not end every sentence the same way — use connective forms to chain related actions and thoughts into longer, flowing sentences where natural.`,
      `- Once a subject is established, omit it in subsequent sentences unless switching subject or avoiding ambiguity. Do not repeat any subject — 少女、二人、少年 — in consecutive sentences.`,
      `- Do not use 彼女 or 彼 as pronouns. Refer to characters by their established name or noun (少女、少年 etc.), or drop the subject entirely.`,
      `- Avoid stacking more than two の particles in a single noun phrase. Restructure as a separate clause if needed.`,
      `- Use a mix of sentence lengths. Short sentences work well for impact or dialogue; longer chained sentences carry action and scene-setting.`,
      `- 1–2 lines of dialogue or internal monologue help break up narration and show character reactions naturally.`,
      `- Keep tense consistent within a scene. If you use the historical present for vividness, do so deliberately and consistently — do not switch tense on the same observation.`,
      `- Use vocabulary words in their natural semantic range. Do not apply a word to a context it would never appear in (e.g. 里 for a modern urban neighbourhood).`,
      ``,
      `Story structure:`,
      `- Open with a brief scene or environmental detail that grounds the reader.`,
      `- Build through action and discovery.`,
      `- Use dialogue or internal thought to show character reaction at a key moment.`,
      `- End at a moment of genuine tension — complete your final sentence, but leave the situation unresolved.`,
      ``,
      `Before drafting:`,
      `- In 2–3 English sentences, silently plan: the setting, the characters, the key moment, and how it ends. Do not output this plan.`,
      `- Identify a small subset of the vocabulary list that naturally fits this plan.`,
      ``,
      `Before outputting:`,
      `- Check every content word against the vocabulary list. Rewrite any sentence that uses an out-of-list content word.`,
      `- Check that no subject is repeated in consecutive sentences without good reason.`,
      `- Check that sentence endings vary — if three or more sentences end the same way, revise.`,
      `- Check that narration is in plain form throughout. Rewrite any narrative sentence ending in です or ます.`,
      `- Check that tense is consistent within each scene.`,
      `- Check that each vocabulary word is used within its natural semantic range.`,
      `- Check narrative logic and chronological consistency. Ensure physical actions are not contradicted later without reason (e.g. a character who clearly values an object should not abandon it without explanation). If the prompt requires a character to remember a past event, that event must have happened before the current scene — not during it.`,
      ``,
      `Output only the Japanese story, no preamble.`,
    ].join("\n");

    let raw = "";
    await storyAdapter.stream(
      systemPrompt,
      `Known vocabulary list:\n${wordList}\n\n${storyContext}`,
      { thinkingConfig: { thinkingBudget: 0 } },
      chunk => { raw += chunk; send("delta", chunk); }
    );

    send("done", { tokens: tokenize(raw) });

  } catch (err) {
    console.error(err);
    send("error", err.message || "Generation failed");
  } finally {
    res.end();
  }
});

// ── Dictionary lookup (local JMdict) ────────────────────────────────────────

app.get("/api/dict", (req, res) => {
  const { word } = req.query;
  if (!word) return res.status(400).json({ error: "word required" });
  if (!dictStmt) return res.json({ found: false });
  const row = dictStmt.get(word);
  if (!row) return res.json({ found: false });
  res.json({
    found:         true,
    reading:       row.reading,
    meanings:      JSON.parse(row.meanings),
    partsOfSpeech: JSON.parse(row.pos),
  });
});

app.post("/api/explain", async (req, res) => {
  const { text, sentence } = req.body;
  if (!text) return res.status(400).json({ error: "text required" });

  try {
    const explanation = await enhanceAdapter.generate(
      "You are a Japanese grammar tutor helping a WaniKani learner read a story. " +
      "The learner has highlighted a word or phrase. Explain in 1-2 sentences how it works in THIS specific sentence. " +
      "Ground your explanation in the actual content of the sentence — name the real subject, object, or situation rather than speaking abstractly about 'the action' or 'the verb'. " +
      "Do NOT give a generic grammar explanation that could apply to any sentence. " +
      "Do NOT restate the dictionary meaning or give the reading. " +
      "Start directly with the grammatical function as it plays out in this sentence. " +
      "Plain English. No intro phrases.",
      `Sentence: ${sentence}\nHighlighted: ${text}`,
      { thinkingConfig: { thinkingBudget: 0 }, maxOutputTokens: 200 }
    );
    res.json({ explanation: explanation.trim() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.listen(PORT, "0.0.0.0", () => console.log(`http://localhost:${PORT}`));
